import type { Metadata } from "next";
import { Noto_Serif_Bengali, Inter } from "next/font/google";
export const dynamic = 'force-dynamic';
import "./globals.css";
import ScrollToTopBottom from "@/components/scrollToTopBottom/scrollToTopBottom";

const notoSerifBengali = Noto_Serif_Bengali({
    variable: "--font-noto-serif-bengali",
    subsets: ["bengali"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ['latin'],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "News Paper Home Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${notoSerifBengali.variable} ${inter.variable} antialiased`}
            >
                <ScrollToTopBottom />
                {children}
            </body>
        </html>
    );
}
