import type { Metadata } from "next";
import Notification from "@/components/notification/notification";

export const metadata: Metadata = {
    title: "News Flash 71 User Registration",
    description: "Generated by create next app",
};

export default function UserRegistrationLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <Notification />
            {children}
        </main>
    );
}
