import type { Metadata } from "next";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
    title: "News Flash 71 Latest Web Storis News",
    description: "Generated by create next app",
};

export default function WebStorisNewsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <Header />
            {children}
            <Footer />
        </main>
    );
}
