import type { Metadata } from "next";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
    title: "News Paper Terms of Service Page",
    description: "Generated by create next app",
};

export default function TermsofServiceLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    );
}
